@startuml
UI -> ViewModel:入力画像を伝える(Bitmap)
ViewModel -> UseCase:識別を依頼(List<Float>)
UseCase -> Repository:識別を依頼(Domain層のImage)
Repository -> TFLiteModel:識別を依頼(TensorBuffer)
TFLiteModel -> Repository:識別結果を返す(TensorBuffer)
Repository -> UseCase:識別結果を返す(Domain層のClassifyResult)
UseCase -> ViewModel:識別結果を返す(Domain層のClassifyResult))
ViewModel -> UI:UiStateを更新して伝える(UiState)
@enduml